spring:
  application:
    name: free-crm
  profiles:
     active: @spring.profiles.active@
  main:
    banner-mode: "off"

server:
  port: 8088
  app:
    email: dyvakyurii@gmail.com
    threadCount: 10

free-crm:
  activate: true

notification:
  email:
    - dyvakyurii@gmail.com
  activate: true

---

spring:
  profiles: development | test
  datasource:
    url: @database.url@
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    properties:
      hibernate.format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  app:
    email: dyvakyurii@gmail.com
    threadCount: 4

---

spring:
  profiles: production

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    properties:
      hibernate.format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update





