spring:
  profiles: production

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    properties:
      hibernate.format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: update