server:
  app:
    email: dyvakyurii@gmail.com
    threadCount: 4

spring:
  application:
    name: crm
  profiles: development
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    properties:
      hibernate.format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: @database.main.url@
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate: DEBUG
  mail:
    host: smtp.gmail.com
    port: 465
    username: dyvakyurii
    password: pentagon@gala.net
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true